FROM ruby:2.3.3

RUN apt-get update && \
    apt-get install -y nodejs wget bzip2 libfontconfig build-essential && \
    apt-get clean

RUN useradd -m -d /usr/src/app/ publicapp
WORKDIR /usr/src/app/

COPY Gemfile Gemfile.lock ./
RUN bundle install

EXPOSE 3000
