FROM ruby:2.3.3

RUN apt-get update && \
    apt-get install -y nodejs wget bzip2 libfontconfig build-essential && \
    apt-get clean

#install phantom
RUN mkdir /tmp/phantomjs \
   && curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
       | tar -xj --strip-components=1 -C /tmp/phantomjs \
   && mv /tmp/phantomjs/bin/phantomjs /usr/local/bin

RUN useradd -m -d /usr/src/app/ publicapp
WORKDIR /usr/src/app/

COPY Gemfile Gemfile.lock ./
RUN bundle install

EXPOSE 3000

COPY . .
